export { default as HeroSection } from "./HeroSection";
export { default as DiscoverSection } from "./DiscoverSection";
export { default as TrendingDestinationsSection } from "./HowItWorksSection";
export { default as OrderWithFork } from "./OrderWithFork";
export { default as GivingBack } from "./GivingBack";
export { default as MediaGallery } from "./MediaGallery";
export { default as ReviewsSection } from "./ReviewsSection";
export { default as FaqSection } from "./FaqSection";
export { default as OfferSection } from "./OfferSection";
